### ISSUE TITLE
Broken links from DynamoDB SDK Examples

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#117]
The links in the tables are not redirecting properly to the respective examples, some links are working but most of them are not working.  https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/README.md

**Comment by plastic-karma** [comment]
Hi, DynamoDB enthusiast here. I could contribute the fix to this issue and correct the links.

**Comment by tebanieo** [comment]
Implemented in #143. Thank you very much @plastic-karma for your contribution.
