### ISSUE TITLE
Schema design - Schema samples - Session Management - Needs Readme

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#132]
Create a readme for this example.

[Gaming profile](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/data-modeling-schema-gaming-profile.html) in the DynamoDB Documentation, we need a simplified version for this readme.

**Comment by davetownG** [comment]
Hi @tebanieo can you assign this to me? Thanks!

**Comment by davetownG** [comment]
Hi @tebanieo, is there a document that we need a simplified version of for the readme? The initial comment is pointing to a Gaming profile doc, rather than Session Management. Thanks!

**Comment by tebanieo** [comment]
I have sent you a private message, please use that as reference.
