### ISSUE TITLE
Schema design - Schema samples - Social Network - Needs Readme

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#133]
The Social Network example needs a readme.

This is the link to the documentation [Social network schema design](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/data-modeling-schema-social-network.html). We need a simplified version for the Readme.

**Comment by davetownG** [comment]
@tebanieo can you assign this issue to me? I don't have permissions to. Thanks

**Comment by davetownG** [comment]
@tebanieo is the [ConnectedVehicles](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/schema_design/SchemaExamples/ConnectedVehicles/README.md) example a good model for what is needed for a Social Network readme?

**Comment by tebanieo** [comment]
> @tebanieo is the [ConnectedVehicles](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/schema_design/SchemaExamples/ConnectedVehicles/README.md) example a good model for what is needed for a Social Network readme?

It can be used as a reference, but don't feel that you have to replicate exactly as it is right there, think more of it like a sources for inspiration. Feel free to add more elements to the readme, imagine what kind of context you would like to have before reading the data model.

**Comment by davetownG** [comment]
@tebanieo this can be closed. PR 161 completed it. https://github.com/aws-samples/aws-dynamodb-examples/pull/161

**Comment by tebanieo** [comment]
Thanks @davetownG for your contribution, for future contributions please make sure you add in the PR comment the issue you are working on, for better traceability.
