### ISSUE TITLE
Scripts - Docker - Needs Readme

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#136]
The docker example needs a readme where options and deployment is explained [docker](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/scripts/docker)

**Comment by MohammedAliZaini** [comment]
Hi @tebanieo,

I've created created a README.md file for docker and made a [pull request](https://github.com/aws-samples/aws-dynamodb-examples/pull/139).

I hope this helps :)
