### ISSUE TITLE
Scripts - NoSQLWorkbenchScript - Enhance Readme

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#137]
The current [Readme](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/scripts/nosqlworkbenchscript) needs enhancement, include execution samples and more information to the reader on what to expect from the script.

**Comment by davetownG** [comment]
@tebanieo can you assign this issue to me, I am unable to assign

**Comment by davetownG** [comment]
@tebanieo completed, pull request created
