### ISSUE TITLE
Python Examples - Updating Operations.md

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#142]
This is a summary of the work that needs to be completed on this issue:

- [x] Fix [DeleteItemConditional](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithItems/delete_item2.py) reference to point to `delete_item_conditional.py`.
- [x] Add, [pagination.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/pagination.py), [query-scan-count.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query-scan-count.py), [query_begins_with.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query_begins_with.py) and [query_equals.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query_equals.py) to the [Operations.md](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/Operations.md) file. 
- [x] Identify the examples that matches the `WorkingWithIndexes` description, the examples might also be present under a different category. 
- [x] Add entry for [add_gsi.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/add_gsi.py) and [enable_continuous_backups.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/enable_continuous_backups.py). 
- [x] Renaming [table_change_to_on-demand.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/table_change_to_on-demand.py) and [table_change_to_provisioned.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/table_change_to_provisioned.py) to `update_table_on-demand` and `update_table_provisioned` so it's consistent with what's in Operations.MD
- [x] Add entry for [paginated-query-batch-execute-statement.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithPartiQL/paginated-query-batch-execute-statement.py) and [paginated-select-statement.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithPartiQL/paginated-select-statement.py)
- [x] Add entry for [WorkingWithCustomBackoffRetry](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithCustomBackoffRetry)</b> exists but is not documented in README
- [x] Update `Count` in the table to match [query-scan-count.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query-scan-count.py).

_Originally posted by @tebanieo in https://github.com/aws-samples/aws-dynamodb-examples/issues/124#issuecomment-2355841155_

**Comment by davetownG** [comment]
I would like to work on this issue, but am unable to assign to myself.

**Comment by davetownG** [comment]
All items completed, unable to check off items due to permissions.
