### ISSUE TITLE
DynamoDBEmbedded is not resolving 

### ISSUE THREAD

**Issue by shubham9941** [aws-samples/aws-dynamodb-examples#20]
https://github.com/awslabs/aws-dynamodb-examples/blob/c68fafca35fb4d46fe39364d66593f5ac0b67fdc/src/test/java/com/amazonaws/services/dynamodbv2/local/embedded/DynamoDBEmbeddedTest.java#L44

![image](https://user-images.githubusercontent.com/25051888/35481233-b0d6302e-0445-11e8-8d40-ffd468187079.png)

**Comment by SachinRaghunathan** [comment]
its probably an issue with your maven imports. restart your ide/reimport maven

**Comment by SLYJason** [comment]
A quick fix would be: `import com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded;`
