### ISSUE TITLE
DynamoDBLocal and aws-java-sdk-dynamodb dependency version issue?

### ISSUE THREAD

**Issue by mnkg561** [aws-samples/aws-dynamodb-examples#24]
I have DynamoDBLocal and aws-java-sdk-dynamodb in my pom and when I'm trying to package its throwing errors::

I have tried multiple ways..

1. With the following dependencies

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>DynamoDBLocal</artifactId>
			<version>[1.11.86,2.0)</version>
			<scope>test</scope>
                </dependency>
                <dependency> 
                        <groupId>com.amazonaws</groupId>
                        <artifactId>aws-java-sdk-dynamodb</artifactId> 
			<version>1.11.294</version>
              </dependency>  

I'm getting following exceptions while running unit test case execution..

java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.dynamodbv2.local.shared.mapper.DynamoDBObjectMapper
	at com.amazonaws.services.dynamodbv2.local.server.AbstractLocalDynamoDBServerHandler.<init>(AbstractLocalDynamoDBServerHandler.java:42)

java.lang.NoClassDefFoundError: com/amazonaws/protocol/StructuredPojo

2. If I'm commenting aws-java-sdk-dynamodb dependency and removing test scope from DynamoDBLocal dependency
     a. I'm getting compilation error because I'm using com.amazonaws.services.dynamodbv2.document.ItemUtils in one of my class file
    b. If I comment out the part where I'm using ItemUtils, Unit test cases executed perfectly but unable to complete packaging as a shade jar file with the following error..
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.303 s
[INFO] Finished at: 2018-03-16T23:35:55-07:00
[INFO] Final Memory: 28M/315M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.0:shade (default) on project lambda_ssh_keys_handler: Error creating shaded jar: error in opening zip file /Users/nmogulla/.m2/repository/com/almworks/sqlite4java/libsqlite4java-linux-i386/1.0.392/libsqlite4java-linux-i386-1.0.392.so -> [Help 1]
[ERROR]

**Comment by mnkg561** [comment]
Just an FYI. This issue is while creating a fat jar file using maven shade. Problem starts when we use was-java-sdk-dynamodb version greater than 1.11.93. Something might have changed starting from 1.11.94 which is not compatible with DynamoDBLocal

**Comment by sefo** [comment]
I have the exact same problem. I don't use dynamoDB in the project I try to build and the jar I have in .m2 is version 1.11.86

It's so painful to work with aws...
