### ISSUE TITLE
403: Could not resolve com.amazonaws:DynamoDBLocal:1.+.

### ISSUE THREAD

**Issue by shanemccallbgch** [aws-samples/aws-dynamodb-examples#27]
My project won't download DynamoDBLocal due to a 403.

Could not resolve com.amazonaws:DynamoDBLocal:1.+.
      > Failed to list versions for com.amazonaws:DynamoDBLocal.
         > Unable to load Maven meta-data from https://s3-us-west-2.amazonaws.com/dynamodb-local/release/com/amazonaws/DynamoDBLocal/maven-metadata.xml.
            > Could not GET 'https://s3-us-west-2.amazonaws.com/dynamodb-local/release/com/amazonaws/DynamoDBLocal/maven-metadata.xml'. Received status code 403 from server: Forbidden

I've tried my local S3 URL as well and 403 https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/release

**Comment by CCBow-501** [comment]
+1
 Jenkins cant download it either. Right now all my builds are failing.

**Comment by dkobia** [comment]
All the repos listed here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.Maven.html seem to be inaccessible.

**Comment by dkobia** [comment]
Looks like its been resolved?

**Comment by shanemccallbgch** [comment]
It does except for https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/release

**Comment by CCBow-501** [comment]
https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/release does work for me

**Comment by shanemccallbgch** [comment]
Weird I get:
`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>release</Key>
<RequestId>7DCC85EEA1AEE7F7</RequestId>
<HostId>
1TWQIOS76SSL4h3vQt34inUnOryOWnkQyytGf28Bh9ECMUbOXRIC4GbMQjT9F2L36h+dtl/hpRY=
</HostId>
</Error>`
