### ISSUE TITLE
Could not find com.amazonaws:DynamoDBLocal

### ISSUE THREAD

**Issue by github4sanjay** [aws-samples/aws-dynamodb-examples#34]

**Comment by NoSQLKnowHow** [comment]
Can you be more specific on where this is in the repo? What script or scripts?

Usually to use DynamoDB local, you have to change the endpoint to point to it instead of a region.

**Comment by github4sanjay** [comment]
testImplementation 'com.amazonaws:DynamoDBLocal:1.11.477'
we are not able to download this dependency

**Comment by github4sanjay** [comment]
any update on this ?

**Comment by NoSQLKnowHow** [comment]
Please refer to the Apache Maven tab/section on [this page](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html). If you follow those instructions and still cannot get it to work, please post them in the [DynamoDB forum](https://forums.aws.amazon.com/forum.jspa?forumID=131). You should be able to get help on this far faster than posting in this unrelated github repo.
