### ISSUE TITLE
Enhancement - Social Network example using dynamodb

### ISSUE THREAD

**Issue by johndpope** [aws-samples/aws-dynamodb-examples#56]
From reading up online (stackoverflow) - it seems that dynamodb is unfit for a twitter like setup.  
Is this true? Did anyone attempt? Is this still the case today?

**Comment by NoSQLKnowHow** [comment]
This is not an enhancement, nor does it have anything to do with this repository's content.

**Comment by johndpope** [comment]
Where to find example of dynamodb that handle this? Or it can’t?
