### ISSUE TITLE
Question: any way to run all of the examples one by one

### ISSUE THREAD

**Issue by tzach** [aws-samples/aws-dynamodb-examples#60]
For example using local DynamoDB docker?

**Comment by zachjonesnoel** [comment]
@tzach you can install it locally or run a Docker on your local machine. Check the [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html)

**Comment by tzach** [comment]
Thanks
I was wondering if there is a script to run *all* the examples, one by one, with a local docker.

**Comment by NoSQLKnowHow** [comment]
Can you please help me understand more about the value of having such a script? I ask this as the code in this repo is simply meant to be example code for developers to use to see how various API and PartiQL calls might be done.

**Comment by tzach** [comment]
Looking for a way to use the example with  https://github.com/scylladb/scylla/blob/master/docs/alternator/alternator.md, with the least amount of effort.
Closing this issues, as it seem non relevant for your project.
