### ISSUE TITLE
why the document is not fine

### ISSUE THREAD

**Issue by xuehanxin** [aws-samples/aws-dynamodb-examples#61]
i use dynamodb ,but i cant not find the demo and useage anywhere!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by zachjonesnoel** [comment]
Hi @xuehanxin, so you are using DynamoDB but you aren't able to find demo/snippets of how to use DynamoDB? 

You can find the sample snippets for different languages such as JS, Python, C# and more in [Sample snippets](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/DynamoDB-SDK-Examples), there are references to the respective snippet of code. 

Hope this helps!
