### ISSUE TITLE
Idea / Question: Write Sharding Example

### ISSUE THREAD

**Issue by rohanmeh** [aws-samples/aws-dynamodb-examples#70]
I wrote up a simple example for Write Sharding based on this doc: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-sharding.html

Current "functionality" in the script:

1. Write items with randomized suffix
2. Get all items for randomized suffix (1 query per suffix)
3. Write items with calculated suffix
4. Get items with a calculated suffix

Questions:
1. Would this be a good example for the repo?
2. Currently my script has both writing and reading, should I break it up into multiple parts?
3. I'm not sure which section it should go under. WorkingWithItems?

**Comment by NoSQLKnowHow** [comment]
@rohanmeh Query is by far the most visited topic, followed by scan. So if you wanted to go along with that, giving examples of a write sharded data model, but using Query to assemble the items you need and have it optimized for cost would be a great example!
