### ISSUE TITLE
Create WorkingWithStreams examples for Node.js

### ISSUE THREAD

**Issue by NoSQLKnowHow** [aws-samples/aws-dynamodb-examples#72]
Create example code for working with DynamoDB Streams in Node.js and DynamoDB.

**Comment by ryansonshine** [comment]
I'll take this one

**Comment by ryansonshine** [comment]
I can take this one

**Comment by NoSQLKnowHow** [comment]
Yep, sorry @ryansonshine I have a few more issues to open and I will tag you so you can look at them too. thank you for the interest!
