### ISSUE TITLE
Create an example in node.js of PartiQL and pagination

### ISSUE THREAD

**Issue by NoSQLKnowHow** [aws-samples/aws-dynamodb-examples#73]
Create an example of doing pagination with PartiQL in the Node.js/WorkingWithPartiQL directory.

**Comment by NoSQLKnowHow** [comment]
This issue is closed with the merge,

**Comment by NoSQLKnowHow** [comment]
I am getting errors with this code.

/usr/local/bin/node /Users/kirkcon/GitHub/aws-dynamodb-examples/DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/paginated-all-data.js
/Users/kirkcon/GitHub/aws-dynamodb-examples/DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/paginated-all-data.js:18
        let response = await dbclient.executeStatement(params);

SyntaxError: await is only valid in async functions and the top level bodies of modules

**Comment by NoSQLKnowHow** [comment]
Now the async is saying it is not a function. It needs a ; at the end of the "let params = { }" line.

Though even once I get this to run, it does now show data of any table I connect it to and it is an endless loop.

----------- start of page ---------------
{}
----------- start of page ---------------
{}
----------- start of page ---------------
{}

What am I doing wrong?

**Comment by zachjonesnoel** [comment]
Not quiet sure, however on my local system 14., 16.x and on Lambda function with runtime 14.x I was able to get the response. Yes the ";" is missed I've added that and checked it. 
![image](https://user-images.githubusercontent.com/12515425/140168662-2e7f0511-a763-4d91-ac91-5c5ee619cf25.png)
